### ISSUE TITLE
Morphman && native sentence sound

### ISSUE THREAD

**Issue by Digital-Coder** [ll-in-anki/Danish-8000-Sentences-Revamped#2]
Hejsa.
please update description so that people would know about morphman. I have discovered it today and it could have saved me sooo much time. Another thing maybe you have found sentences with native sound ? There are services like https://forvo.com which mostly has words and https://tatoeba.org/eng/ which unfortunately does not have danish now. https://www.danishclass101.com/ has some sentences with native audio ,but I am not sure how to grab text with audio automatically.

**Comment by jeprecated** [comment]
Hey mate. Thanks for the feedback.

I'll be sure to add a description of Morphman, along with links, to the deck description :+1: it has greatly helped me too.

Native sound is of course much better! But for a deck this size, it would take some considerable effort to get it all switched over (if one can find all the audio!). I will happily take Pull Requests which update the audio to be better, but I am not focusing on improving it myself at this point.

Tak skal du have!

**Comment by jeprecated** [comment]
@Digital-Coder Done :+1: The page has been updated https://ankiweb.net/shared/info/2018379287

Let me know if you have any feedback on the wording of things, and I may incorporate it in :+1:

**Comment by jeprecated** [comment]
And as is now mentioned in the AnkiWeb description, I also took this opportunity to upgrade the repo to [Brain Brew](https://github.com/ohare93/brain-brew), my Anki<->Source control management tool. You will find all the notes are now stored in csv format in this repo, which makes them much easier to edit and view :grin: also one can transform their own cards to and from this csv format, using Brain Brew.

Let me know if you have any questions on that, if you're interested :+1:
